apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
  labels:
    app: hello-server
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - name: hello-server
        image: harbor.edu.cn/nju33/hello-server:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: docker-harbor-nju33

