apiVersion: v1
kind: Service
metadata:
  name: hello-server
  namespace: nju33
  labels:
    app: hello-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: tcp
      protocol: TCP
  selector:
    app: hello-server

